name: school_inspection_app
description: A new Flutter project.
publish_to: 'none' # This ensures the package is private

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

  # 🔧 Device features
  camera: ^0.10.6
  geolocator: ^10.1.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.4.0
  path: ^1.9.0

  # 📱 UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed in future
  # assets:
  #   - assets/images/
